name: 'Setup Python with uv'
description: 'Setup Python, uv, and install dependencies with caching'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  cache-key-suffix:
    description: 'Suffix for cache key'
    required: false
    default: ''
  install-dev:
    description: 'Install development dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.install-dev }}" = "true" ]; then
          uv sync --all-extras --dev
        else
          uv sync --all-extras
        fi
